inherit_from:
  - style/ruby/style.yml

Rails:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

Documentation:
    Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

ClassLength:
  Max: 150